management:
  server:
    port: ${HEALTHCHECK_PORT}

server:
  port: ${AUTH_SERVICE_PORT}

app:
  token:
    secret: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    issuer: http://localhost/
    audience: http://localhost/
    claimName: http://localhost/
    ttl: 604800000
  services:
    auth: false

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/stage
    username: user
    password: password

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_USER}:${DISCOVERY_PASSWORD}@${DISCOVERY_HOST}:${DISCOVERY_PORT}/eureka/
