management:
  server:
    port: ${HEALTHCHECK_PORT}

server:
  port: ${AUTH_SERVICE_PORT:8080}

app:
  token:
    secret: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    issuer: http://localhost/
    audience: http://localhost/
    claimName: http://localhost/
    ttl: 604800000
  services:
    auth: false

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_USER}:${DISCOVERY_PASSWORD}@${DISCOVERY_HOST}:${DISCOVERY_PORT}/eureka/
