server:
  port: ${AUTH_SERVICE_PORT}

app:
  token:
    secret: ${JWT_SECRET}
    issuer: ${JWT_ISSUER}
    audience: ${JWT_AUDIENCE}
    ttl: ${JWT_TTL}
  services:
    auth: false

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: true
  r2dbc:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

eureka:
  client:
    fetch-registry: true
