management:
  server:
    port: ${HEALTHCHECK_PORT}

server:
  port: ${AUTH_SERVICE_PORT}

app:
  token:
    secret: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    issuer: http://localhost/
    audience: http://localhost/
    claimName: http://localhost/
    ttl: 604800000
  services:
    auth: false
  security:
    service-credentials:
      - name: TEST_USER_1
        password: TEST_USER_PASS_1
      - name: TEST_USER_2
        password: TEST_USER_PASS_2

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: true
  r2dbc:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_USER}:${DISCOVERY_PASSWORD}@${DISCOVERY_HOST}:${DISCOVERY_PORT}/eureka/
