server:
  port: ${DISCOVERY_PORT}

spring:
  security:
    user:
      name: ${DISCOVERY_USER}
      password: ${DISCOVERY_PASSWORD}
      role: ${DISCOVERY_ROLE:SYSTEM}

eureka:
  instance:
    hostname: ${DISCOVERY_HOST}
  client:
    registerWithEureka: false
    fetchRegistry: false
