management:
  server:
    port: ${HEALTHCHECK_PORT}

server:
  port: ${HOSPITAL_SERVICE_PORT}
  servlet:
    context-path: /api/hospital

services:
  auth: http://auth-service:8080/api/auth

eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_USER}:${DISCOVERY_PASSWORD}@${DISCOVERY_HOST}:${DISCOVERY_PORT}/eureka/
