management:
  server:
    port: ${HEALTHCHECK_PORT}

server:
  port: ${HOSPITAL_SERVICE_PORT}

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_USER}:${DISCOVERY_PASSWORD}@${DISCOVERY_HOST}:${DISCOVERY_PORT}/eureka/
