server:
  port: ${TIMETABLE_SERVICE_PORT}

app:
  services:
    timetable: false

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: true
  r2dbc:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

eureka:
  client:
    fetch-registry: true
