server:
  port: ${CONFIG_PORT}

spring:
  profiles:
    active: native
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/configs
  security:
    user:
      name: ${CONFIG_USER}
      password: ${CONFIG_PASSWORD}
      roles:
        - ${CONFIG_ROLE:SYSTEM}
